language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: tcG5O4cEFg6xArnf4f+ol1IYD0gv+Mws22A1p6hAhxccIRq3X9IdTtyTpMz48ORU5+ltNy1dg5WvTVLYHBqiZ/S3R/dQQ+gR7v32FjRE36Go71oQ8m3qlDmbGCbutRbuTWd8rUe619Osq11yoQtgg4MuvBSTK/LOkC8htn2DwdWakb9sYCIv4Y2opKeN+Vyql1WeDQYPlwEkpHRGIAGa/TfLYjtj0YTt/55BaDVB1xZlQi4OKYSgb+s1VyH5ZYimO73WKg9mJdur8Qd3htnziafBnON5c3KhRMgN8O8aei601sIBfzWVjPzX72N7KEh7a1tmOxslIvETD4PQVEVa5Y8cBbsWqWl0kAa65KOLgGn+YbFZP06Bh0Fy745TfH0c6JmHbUug5DGWpsBSQ8Ra2Uxa8t9Z2FXZ0VjBPnCLnKT1dcfOsGw4LNiPgPF9xJ1aINfcE/Bx/VOSLfGHJkjLShvQQtRYMDBMe5ZAZpLNV+pTyg746jwSm2cKrmuEmohPAKZItlXqhh5QiPHhvWhO90PyGAkjt4YRDOoqgzaQpPDmAh02aqAPB7yeQ52B4LZke1OtQhbZLMvCkcRpjJz0HPTwKF98v1WurLo/hLi69tZSLeIwuts8be0PNXa+rFTaXLqGqo75Dh0mPIA1c6tiIQN3Lcgwv6Jox3VEK0f6nFc=
  app: meal-revival-server
  on:
    repo: rjwilliams87/meal-revival-server
